### ISSUE TITLE
无法部署：ReferenceError: document is not defined

### ISSUE THREAD

**Issue by DestoryG** [iRedScarf/onedrive-index#26]
Vercel编译报错无法部署，日志：
```
[19:51:52.063] Running build in Washington, D.C., USA (East) – iad1
[19:51:52.174] Cloning [库链接]
[19:51:52.183] Skipping build cache, deployment was triggered without cache.
[19:51:52.828] Cloning completed: 653.915ms
[19:51:53.228] Running "vercel build"
[19:51:53.662] Vercel CLI 39.1.1
[19:51:54.116] Detected `pnpm-lock.yaml` version 6.1 generated by pnpm@8.x
[19:51:54.122] Running "install" command: `pnpm install`...
[19:51:58.655] Lockfile is up to date, resolution step is skipped
[19:51:58.741] Progress: resolved 1, reused 0, downloaded 0, added 0
[19:51:58.901] Packages: +702
[19:51:58.902] ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
[19:51:59.742] Progress: resolved 702, reused 0, downloaded 21, added 8
[19:52:00.743] Progress: resolved 702, reused 0, downloaded 39, added 23
[19:52:01.745] Progress: resolved 702, reused 0, downloaded 111, added 95
[19:52:02.751] Progress: resolved 702, reused 0, downloaded 126, added 111
[19:52:03.752] Progress: resolved 702, reused 0, downloaded 132, added 119
[19:52:04.752] Progress: resolved 702, reused 0, downloaded 139, added 125
[19:52:05.753] Progress: resolved 702, reused 0, downloaded 149, added 135
[19:52:06.754] Progress: resolved 702, reused 0, downloaded 200, added 187
[19:52:07.754] Progress: resolved 702, reused 0, downloaded 262, added 246
[19:52:08.756] Progress: resolved 702, reused 0, downloaded 337, added 328
[19:52:09.757] Progress: resolved 702, reused 0, downloaded 384, added 370
[19:52:10.758] Progress: resolved 702, reused 0, downloaded 480, added 464
[19:52:11.759] Progress: resolved 702, reused 0, downloaded 614, added 600
[19:52:12.765] Progress: resolved 702, reused 0, downloaded 691, added 677
[19:52:13.003] Progress: resolved 702, reused 0, downloaded 702, added 702, done
[19:52:13.221] .../fontawesome-common-types postinstall$ node attribution.js
[19:52:13.233] .../core-js@3.27.2/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
[19:52:13.243] .../es5-ext@0.10.62/node_modules/es5-ext postinstall$  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
[19:52:13.244] .../core-js@3.31.1/node_modules/core-js postinstall$ node -e "try{require('./postinstall')}catch(e){}"
[19:52:13.312] .../fontawesome-common-types postinstall: Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
[19:52:13.313] .../fontawesome-common-types postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
[19:52:13.314] .../fontawesome-common-types postinstall: Copyright 2023 Fonticons, Inc.
[19:52:13.320] .../fontawesome-common-types postinstall: Done
[19:52:13.335] .../core-js@3.27.2/node_modules/core-js postinstall: Done
[19:52:13.358] .../core-js@3.31.1/node_modules/core-js postinstall: Done
[19:52:14.370] .../es5-ext@0.10.62/node_modules/es5-ext postinstall: Done
[19:52:15.065] .../@fortawesome/free-brands-svg-icons postinstall$ node attribution.js
[19:52:15.066] .../@fortawesome/fontawesome-svg-core postinstall$ node attribution.js
[19:52:15.066] .../@fortawesome/free-solid-svg-icons postinstall$ node attribution.js
[19:52:15.066] .../@fortawesome/free-regular-svg-icons postinstall$ node attribution.js
[19:52:15.124] .../esbuild@0.17.4/node_modules/esbuild postinstall$ node install.js
[19:52:15.150] .../@fortawesome/free-brands-svg-icons postinstall: Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
[19:52:15.150] .../@fortawesome/free-brands-svg-icons postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
[19:52:15.151] .../@fortawesome/free-brands-svg-icons postinstall: Copyright 2023 Fonticons, Inc.
[19:52:15.157] .../@fortawesome/free-brands-svg-icons postinstall: Done
[19:52:15.197] .../@fortawesome/fontawesome-svg-core postinstall: Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
[19:52:15.197] .../@fortawesome/fontawesome-svg-core postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
[19:52:15.197] .../@fortawesome/fontawesome-svg-core postinstall: Copyright 2023 Fonticons, Inc.
[19:52:15.207] .../@fortawesome/fontawesome-svg-core postinstall: Done
[19:52:15.259] .../@fortawesome/free-solid-svg-icons postinstall: Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
[19:52:15.259] .../@fortawesome/free-solid-svg-icons postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
[19:52:15.260] .../@fortawesome/free-solid-svg-icons postinstall: Copyright 2023 Fonticons, Inc.
[19:52:15.272] .../@fortawesome/free-solid-svg-icons postinstall: Done
[19:52:15.295] .../@fortawesome/free-regular-svg-icons postinstall: Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
[19:52:15.296] .../@fortawesome/free-regular-svg-icons postinstall: License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
[19:52:15.296] .../@fortawesome/free-regular-svg-icons postinstall: Copyright 2023 Fonticons, Inc.
[19:52:15.302] .../@fortawesome/free-regular-svg-icons postinstall: Done
[19:52:15.348] .../esbuild@0.17.4/node_modules/esbuild postinstall: Done
[19:52:16.212] 
[19:52:16.213] dependencies:
[19:52:16.213] + @fortawesome/fontawesome-svg-core 6.4.0
[19:52:16.214] + @fortawesome/free-brands-svg-icons 6.4.0
[19:52:16.214] + @fortawesome/free-regular-svg-icons 6.4.0
[19:52:16.214] + @fortawesome/free-solid-svg-icons 6.4.0
[19:52:16.214] + @fortawesome/react-fontawesome 0.2.0
[19:52:16.214] + @headlessui/react 1.7.8
[19:52:16.214] + @tailwindcss/line-clamp 0.4.2
[19:52:16.214] + @vercel/analytics 1.0.1
[19:52:16.215] + awesome-debounce-promise 2.1.0
[19:52:16.216] + axios 1.2.6
[19:52:16.216] + cors 2.8.5
[19:52:16.216] + crypto-js 4.1.1
[19:52:16.216] + csstype 3.1.1
[19:52:16.217] + dayjs 1.11.7
[19:52:16.217] + emoji-regex 10.2.1
[19:52:16.217] + i18next 22.4.9
[19:52:16.217] + ioredis 5.3.0
[19:52:16.217] + jszip 3.10.1
[19:52:16.217] + mpegts.js 1.7.2
[19:52:16.217] + next 13.1.6
[19:52:16.217] + next-i18next 13.0.3
[19:52:16.218] + nextjs-progressbar 0.0.16
[19:52:16.218] + plyr-react 5.1.2
[19:52:16.218] + preview-office-docs 1.0.2
[19:52:16.218] + react 18.2.0
[19:52:16.218] + react-async-hook 4.0.0
[19:52:16.218] + react-audio-player 0.17.0
[19:52:16.218] + react-cookie 4.1.1
[19:52:16.218] + react-copy-to-clipboard 5.1.0
[19:52:16.218] + react-dom 18.2.0
[19:52:16.219] + react-hot-toast 2.4.0
[19:52:16.219] + react-hotkeys-hook 4.3.3
[19:52:16.220] + react-i18next 12.1.4
[19:52:16.220] + react-markdown 8.0.5
[19:52:16.220] + react-reader 1.0.2
[19:52:16.220] + react-syntax-highlighter 15.5.0
[19:52:16.220] + react-use-system-theme 1.1.1
[19:52:16.220] + rehype-katex 6.0.2
[19:52:16.220] + rehype-raw 6.1.1
[19:52:16.220] + remark-gfm 3.0.1
[19:52:16.221] + remark-math 5.1.1
[19:52:16.221] + swr 2.0.3
[19:52:16.221] + use-clipboard-copy 0.2.0
[19:52:16.221] + use-constant 1.1.1
[19:52:16.221] 
[19:52:16.221] devDependencies:
[19:52:16.221] + @types/cors 2.8.13
[19:52:16.221] + @types/crypto-js 4.1.1
[19:52:16.221] + @types/node 18.16.18
[19:52:16.221] + @types/react 18.2.14
[19:52:16.221] + @types/react-copy-to-clipboard 5.0.4
[19:52:16.221] + @types/react-dom 18.0.10
[19:52:16.221] + @types/react-pdf 6.2.0
[19:52:16.221] + @types/react-syntax-highlighter 15.5.6
[19:52:16.221] + autoprefixer 10.4.13
[19:52:16.221] + eslint 8.43.0
[19:52:16.221] + eslint-config-next 13.4.7
[19:52:16.222] + eslint-config-prettier 8.6.0
[19:52:16.222] + i18next-parser 7.6.0
[19:52:16.222] + postcss 8.4.21
[19:52:16.222] + prettier 2.8.3
[19:52:16.222] + prettier-plugin-tailwindcss 0.2.2
[19:52:16.222] + tailwindcss 3.2.4
[19:52:16.222] + typescript 5.1.3
[19:52:16.222] 
[19:52:16.241] Done in 18.3s
[19:52:16.282] Detected Next.js version: 13.1.6
[19:52:16.283] Running "pnpm build"
[19:52:16.773] 
[19:52:16.773] > onedrive-index@0.2.0 build /vercel/path0
[19:52:16.773] > next build
[19:52:16.773] 
[19:52:17.071] (node:228) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
[19:52:17.071] (Use `node --trace-deprecation ...` to show where the warning was created)
[19:52:17.225] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[19:52:17.226] This information is used to shape Next.js' roadmap and prioritize features.
[19:52:17.226] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[19:52:17.226] https://nextjs.org/telemetry
[19:52:17.227] 
[19:52:17.338] info  - Linting and checking validity of types...
[19:52:19.956] DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.
[19:52:26.372] info  - Creating an optimized production build...
[19:52:26.997] Browserslist: caniuse-lite is outdated. Please run:
[19:52:26.998]   npx browserslist@latest --update-db
[19:52:26.998]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[19:52:39.428] Browserslist: caniuse-lite is outdated. Please run:
[19:52:39.429]   npx update-browserslist-db@latest
[19:52:39.429]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[19:52:51.610] info  - Compiled successfully
[19:52:51.611] info  - Collecting page data...
[19:52:53.128] ReferenceError: document is not defined
[19:52:53.128]     at /vercel/path0/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:302:21
[19:52:53.128]     at /vercel/path0/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:311:5
[19:52:53.128]     at /vercel/path0/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:2:83
[19:52:53.128]     at Object.<anonymous> (/vercel/path0/node_modules/.pnpm/plyr@3.7.8/node_modules/plyr/dist/plyr.js:5:3)
[19:52:53.128]     at Module._compile (node:internal/modules/cjs/loader:1546:14)
[19:52:53.128]     at Object..js (node:internal/modules/cjs/loader:1689:10)
[19:52:53.128]     at Module.load (node:internal/modules/cjs/loader:1318:32)
[19:52:53.128]     at Function._load (node:internal/modules/cjs/loader:1128:12)
[19:52:53.128]     at TracingChannel.traceSync (node:diagnostics_channel:315:14)
[19:52:53.128]     at wrapModuleLoad (node:internal/modules/cjs/loader:218:24)
[19:52:53.132] 
[19:52:53.132] > Build error occurred
[19:52:53.133] Error: Failed to collect page data for /[...path]
[19:52:53.133]     at /vercel/path0/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:963:15 {
[19:52:53.133]   type: 'Error'
[19:52:53.133] }
[19:52:53.187]  ELIFECYCLE  Command failed with exit code 1.
[19:52:53.216] Error: Command "pnpm build" exited with 1
[19:52:53.588] 
```

**Comment by DestoryG** [comment]
已解决，问题原因是Nodejs 22弃用了部分命令，更换回Nodejs 20后成功部署
